#defaul 설정
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
    org.hibernate.sql: debug

--- #dev 설정(개발 환경)
spring:
  config:
    activate:
      on-profile: "db-local"

  datasource:
    url: jdbc:mariadb://localhost:3306/firesea
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

--- # production 설정(실제 운영 환경)
spring:
  config:
    activate:
      on-profile: "db-aws"

  datasource:
    url: jdbc:mariadb://clonecoding-db-hs.cscw3xm3rpxf.ap-northeast-2.rds.amazonaws.com:3306/clonecoding-hs
    username: root
    password: eddy8568
    driver-class-name: org.mariadb.jdbc.Driver